package com.androider.kotlin.utils

class Constants{
    companion object{

        const val Username = "username"
        const val Password = "password"
        const val Gender = "gender"
        const val Department = "department"
        const val Class = "class"
        const val UserType = "usertype"
        const val DeviceToken = "devicetoken"
        const val Uid = "uid"
        const val FullName ="fullname"
        const val RegisterNumber = "registernumber"
        const val RollNumber = "rollnumber"
        const val LastLogin = "lastlogin"
        const val Batch = "batch"
        const val PhoneNumber = "phonenumber"
        const val ImageURL = "imageURL"
        const val EmailID ="emailID"
        const val PrimaryAddress ="primaryaddress"
        const val Experience = "experience"
        const val DateOfBirth = "dateofbirth"
        const val FatherName = "fathername"
        const val MotherName = "mothername"
        const val FatherOccupation ="fatheroccupation"
        const val MotherOccupation = "motheroccupation"

        //Store user data after Login
        var TempUsername = ""
        var TempPassword = ""
        var TempGender = ""
        var TempDepartment = ""
        var TempClass = ""
        var TempRollNumber = ""
        var TempRegisterNumber = ""
        var TempUserType = ""
        var TempDeviceToken = ""
        var TempUid = ""
        var TempFullName =""
        var TempLastLogin = ""
        var TempBatch = ""
        var TempPhoneNumber = ""
        var TempImageURL = ""
        var TempEmailID =""
        var TempPrimaryAddress =""
        var TempExperience = ""
        var TempDateOfBirth = ""
        var TempFatherName = ""
        var TempMotherName = ""
        var TempFatherOccupation =""
        var TempMotherOccupation = ""

    }
}